config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'
  resources :animals, :users_infos

  namespace :admin do
    resources :animals, :users_infos
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else if user.confirmed_at
      can :create, Animal
      can :manage, Animal, :user_id => user.id
      can :manage, UsersInfo, :user_id => user.id
    else 
      can :read, Animal
      cannot :manage, Animal
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

end

app/models/animal.rb
class Animal < ActiveRecord::Base
	belongs_to :user

	mount_uploader :animal_picture, AvatarUploader

	before_create :check_user

	before_update :check_owner

	def check_owner
      redirect_to root_path unless can? :manage, Animal 
    end 

    def check_user
      redirect_to root_path unless can? :create, Animal 
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  #include ActiveModel::Dirty


  #after_update :send_welcome_letter 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
    
	has_many :animals
	has_one :user_info



	#def confirmed?
	  #confirmed_at&&confirmed_at_changed?
	#end

	#def send_welcome_letter
      #UserMailer.welcome_letter(email).deliver_now if self.confirmed?
	#end


end

app/models/users_info.rb
class UsersInfo < ActiveRecord::Base
	belongs_to :user
end

app/controllers/admin/animals_controller.rb
class Admin::AnimalsController < ApplicationController

before_action :check_admin
	
def new
	
	@animal = Animal.new
end
def create
	@animal = Animal.new
	@animal.users_id = current_user.id
	@animal.animals_type = params[:animal][:animals_type]
	@animal.breed = params[:animal][:breed]
	#@animal.price = params[:animal][:price]
    @animal.note = params[:animal][:note]
    #@animal.age = params [:animal][:age]
    #@animal.weight = params [:animal][:weight]
    #@animal.height = params [:animal][:height]
    @animal.animal_picture = params[:animal][:animal_picture]
	@animal.save 
	redirect_to admin_animals_path	
end

def index
	@animals_count = Animal.count
	@animals = Animal.all
	@animals = Animal.order(:id).page(params[:page]).per(5)
end

def show
	@animal = Animal.find(params[:id])
end

def edit
	@animal = Animal.find(params[:id])
end

def update
	@animal = Animal.find(params[:id])
	@animal.animals_type = params[:animal][:animals_type]
	@animal.breed = params[:animal][:breed]
	#@animal.price = params[:animal][:price]
    @animal.note = params[:animal][:note]
    #@animal.age = params [:animal][:age]
    #@animal.weight = params [:animal][:weight]
    #@animal.height = params [:animal][:height]
    @animal.animal_picture = params[:animal][:animal_picture]
	@animal.save
	redirect_to admin_animals_path	
end

def destroy
	 Animal.find(params[:id]).destroy
	 redirect_to admin_animals_path
end

def check_admin
	redirect_to root_path unless can? :mamge, Animal
end

end

app/controllers/admin/users_infos_controller.rb
class Admin::UsersInfosController < ApplicationController
end

app/controllers/advert_controller.rb
class AdvertController < ApplicationController
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController


def new
  
  @animal = Animal.new
end
def create
  @animal = Animal.new
  @animal.users_id = current_user.id
  @animal.animals_type = params[:animal][:animals_type]
  @animal.breed = params[:animal][:breed]
  #@animal.price = params[:animal][:price]
  @animal.note = params[:animal][:note]
  #@animal.age = params [:animal][:age]
  #@animal.weight = params [:animal][:weight]
  #@animal.height = params [:animal][:height]
  @animal.animal_picture = params[:animal][:animal_picture]
  @animal.save 
  redirect_to animals_path  
end

def index
  @animals_count = Animal.count
  @animals = Animal.all
end

def show
  @animal = Animal.find(params[:id])
end

def edit
  @animal = Animal.find(params[:id])
end

def update
  @animal = Animal.find(params[:id])
  @animal.animals_type = params[:animal][:animals_type]
  @animal.breed = params[:animal][:breed]
  #@animal.price = params[:animal][:price]
  @animal.note = params[:animal][:note]
  #@animal.age = params [:animal][:age]
  #@animal.weight = params [:animal][:weight]
  #@animal.height = params [:animal][:height]
  @animal.animal_picture = params[:animal][:animal_picture]
  @animal.save
  redirect_to animals_path  
end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/available_animals_controller.rb
class AvailableAnimalsController < ApplicationController
  def new
  	@available_animal = AvailableAnimal.new
  end

  def create
    authenticate_user!
  	@available_animal = AvailableAnimal.new
  	@available_animal.user_id = current_user.id
  	@available_animal.description = params[:available_animal][:description]
  	@available_animal.note = params[:available_animal][:note]
  	@available_animal.price = params[:available_animal][:price]
  	@available_animal.quantity = params[:available_animal][:quantity]
  	@available_animal.age = params[:available_animal][:age]
  	@available_animal.weight = params[:available_animal][:weight]
  	@available_animal.height = params[:available_animal][:height]
  	@available_animal.save
  	redirect_to available_animals_path
  	
  end

  def index
  	@available_animals = AvailableAnimal.all
  	@available_animals_count = AvailableAnimal.count
  end

  def show
  	@available_animal = AvailableAnimal.find(params[:id])
  end

  def edit
  	@available_animal = AvailableAnimal.find(params[:id])
  end

  def update
  	@available_animal = AvailableAnimal.find(params[:id])
  	@available_animal.description = params[:available_animal][:description]
  	@available_animal.note = params[:available_animal][:note]
  	@available_animal.price = params[:available_animal][:price]
  	@available_animal.quantity = params[:available_animal][:quantity]
  	@available_animal.age = params[:available_animal][:age]
  	@available_animal.weight = params[:available_animal][:weight]
  	@available_animal.height = params[:available_animal][:height]
  	@available_animal.save
    redirect_to available_animals_path
  end

  def destroy
  	@available_animal = AvailableAnimal.find(params[:id]).destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
end

app/controllers/users_infos_controller.rb
class UsersInfosController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/advert_helper.rb
module AdvertHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/users_infos_helper.rb
module UsersInfosHelper
end

app/views/admin/animals/_animal.html.erb
	<tr>
	  <td><%= image_tag(animal.animal_picture) if animal.animal_picture? %></td>
	  <td><%= animal.id %></td>
	  <td><%= animal.breed %></td>
	  <td><%= animal.animals_type %></td>
	  <td><%= animal.note %></td>
	  <td><%= link_to('Просмотреть', admin_animal_path(id: animal.id)) %></td>
	  <td><%= link_to('Редактировать', edit_admin_animal_path(id: animal.id) ) %></td>
	  <td><%= link_to('Удалить', admin_animal_path(id: animal.id), method: :delete ) %></td>
	</tr>

app/views/admin/animals/_form.html.erb
<%= form_for [:admin, @animal]  do |form| %>


  <!--<%= form.label :id %>
  <%= form.text_field :id %>-->

  <%= form.label :animals_type, 'Вид' %>
  <%= form.text_field :animals_type %>

  <%= form.label :breed, 'Порода' %>
  <%= form.text_field :breed %>

  <%= form.label :description, 'Название объявления' %>
  <%= form.text_field :description %>

  <%= form.label :age, 'Возраст' %>
  <%= form.text_field :age %>

  <%= form.label :weight, 'Вес' %>
  <%= form.text_field :weight %>

  <%= form.label :height, 'Рост' %>
  <%= form.text_field :height %>

  <%= form.label :note, 'Подробное описание' %>
  <%= form.text_area :note %>


  <%= form.submit 'Сохранить' %>
<%- end %>

app/views/admin/animals/index.html.erb
<h1>База животных </h1>
<p></p>
<p></p>
<p> количество типов животных в базе <%= @animals_count  %></p>
<p></p>
<%= link_to('Добавить объявление', new_admin_animal_path)  %>
<p></p>

<table>
	
	<tbody id="animals">
		

		<%= render @animals %>			

	</tbody>
</table>
<div id="paginator">
			<%= paginate @animals, :remote => true %>
</div>

app/views/admin/animals/index.js.erb
$('#animals').html('<%= escape_javascript render(@animals) %>');
$('#paginator').html('<%= escape_javascript(paginate(@animals, :remote => true).to_s) %>');

app/views/admin/available_animals/_form.htm.erb
<%= form_for  @available_animal do |form| %>




  <%= form.label :description, 'Заголовок' %>
  <%= form.text_field :description %>

  <%= form.label :price , 'Цена' %>
  <%= form.text_field :price %>

  <%= form.label :quantity , 'Количество' %>
  <%= form.text_field :quantity %>

  <%= form.label :note , 'Описание' %>
  <%= form.text_field :note %>

  <%= form.label :age , 'Возраст' %>
  <%= form.text_field :age %>

  <%= form.label :weight , 'Вес' %>
  <%= form.text_field :weight %>

  <%= form.label :height , 'Рост' %>
  <%= form.text_field :height %>

  <%= form.submit 'Сохранить' %>
<%- end %>

<!-- t.integer  "animal_id"
    t.float    "price"
    t.integer  "quantity"
    t.text     "note"
    t.text     "animal_picture"
    t.date     "last_show_date"
    t.float    "age"
    t.float    "weight"
    t.float    "height"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.integer  "user_id"
    t.string   "description" -->

app/views/animals/_form.html.erb
<%= form_for [:admin, @animal]  do |form| %>

  <table>
  <tr>
  <td><%= form.label :animals_type, 'Вид' %></td>
  <td><%= form.text_field :animals_type %></td>
  </tr>

  <tr>
  <td><%= form.label :breed, 'Порода' %></td>
  <td><%= form.text_field :breed %></td>
  </tr>
  
  <!--
  <tr>
  <td> <%= form.label :price, 'Цена, грн' %> </td>
  <td> <%= form.number_field :age %> </td>
  </tr>

  <tr>
  <td> <%= form.label :age, 'Возраст, полных лет' %> </td>
  <td> <%= form.number_field :age %> </td>
  </tr>

  <tr>
  <td> <%= form.label :weight, 'Вес, кг' %> </td>
  <td> <%= form.number_field :weight %> </td>
  </tr>

  <tr>
  <td> <%= form.label :height, 'Рост, см' %> </td>
  <td> <%= form.number_field :height %> </td>
  </tr>
  -->

  <tr>
  <td> <%= form.label :note, 'Подробное описание' %> </td>
  <td> <%= form.text_area :note %> </td>
  </tr>

  <tr>
  <%= image_tag(@animal.animal_picture) if @animal.animal_picture? %>
  <%= form.file_field :animal_picture %>
  <%= form.hidden_field :animal_picture_cache %>
  </tr>


  <tr>
  <td> <%= form.submit 'Сохранить' %></td>
  <td> </td>
  </tr>

  </table>
<%- end %>

app/views/animals/edit.html.erb
<%= render partial: 'form' %>

app/views/animals/index.html.erb
<h1>Справочник животных</h1>
<p></p>
<p> количество типов животных в базе <%= @animals_count  %></p>
<p></p>
<%= link_to('Добавить объявление', new_animal_path)  %>
<p></p>
<table>
	<%- @animals.each do |animals| %>


	<tr>
	  <td><%= image_tag(animals.animal_picture) if animals.animal_picture? %></td>
	  <td><%= animals.breed %></td>
	  <td><%= animals.animals_type %></td>
	  <td><%= animals.note %></td>
	  <td><%= link_to('Просмотреть', admin_animal_path(id: animals.id)) %></td>
	  <% if can? :manage, Animal %>
	    <td><%= link_to('Редактировать', edit_animal_path(id: animals.id) ) %></td>
	    <td><%= link_to('Удалить',animal_path(id: animals.id), method: :delete ) %></td>
	   <%-end %>
	</tr>

	<%- end %>
</table>

app/views/animals/new.html.erb
<%= render partial: 'form' %>

app/views/animals/show.html.erb
<h1><%= @animal.animals_type  %></h1>

<ul>
	<li><%= @animal.animals_type %></li>
	<li><%= @animal.breed %></li>
</ul>

<%= link_to('Вернуться к списку животных ', admin_animals_path) %>

app/views/available_animals/_form.html.erb
<%= form_for  @available_animal do |form| %>




  <p> <%= form.label :description, 'Заголовок' %>
  <%= form.text_field :description %> </p>

  <p> <%= form.label :price , 'Цена' %>
  <%= form.text_field :price %></p>

  <p> <%= form.label :quantity , 'Количество' %>
  <%= form.text_field :quantity %> </p>

  <p> <%= form.label :note , 'Описание' %>
  <%= form.text_field :note %> </p>

  <p><%= form.label :age , 'Возраст' %>
  <%= form.text_field :age %> </p>

  <p> <%= form.label :weight , 'Вес' %>
  <%= form.text_field :weight %> </p>

  <p> <%= form.label :height , 'Рост' %>
  <%= form.text_field :height %> </p>

  <p> <%= form.submit 'Сохранить' %> </p>
<%- end %>

<!-- t.integer  "animal_id"
    t.float    "price"
    t.integer  "quantity"
    t.text     "note"
    t.text     "animal_picture"
    t.date     "last_show_date"
    t.float    "age"
    t.float    "weight"
    t.float    "height"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.integer  "user_id"
    t.string   "description" -->

app/views/available_animals/index.html.erb
<h1>Список объявлений</h1>>
<p> Количество объявлений на сайте <%= @available_animals_count %> </p>

app/views/home/index.html.erb
<h1>Animalstrade</h1>
<p>Здравствуйте, Сейчас Наша доска электронных обьявлений находится в разработке</p>
<p> <%= link_to('Просмотр объявлений', animals_path ) %></p> 
<% if can? :manage, Animal %>
  <%= link_to "Управление объявлениями",  admin_animals_path%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeworkRor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


<%= yield %>

</body>
</html>

app/views/main_page/index.html.erb
<table>
	<tr>
	  <td colspan="1" >Шаповалов Евгений Андреевич</td>
	  	
	</tr>
	<tr>
	  <td><%=image_tag("avatar.jpg")  %></td>
	  <td id = "menu">
	  <div>
	  <p><%=link_to "Обо мне", "#" %></p>
	  <p><%=link_to "Мои работы", "#" %></p>	
	  <p><%=link_to "Сделать заказ", "#" %></p>
	  <p><%=link_to "Контакты", "#" %></p>	
	  </div>	
	  </td>	
	</tr>
</table>